export const lightTheme = {
  mode: 'light',
  colors: {
    pageBg: '#EAEEF6',
    wrapperBg: '#F1F1F1',
    headerBg: '#FFFFFF',
    cardBg: '#FFFFFF',
    text: '#000000',
    mutedText: '#94A6BE',
    primary: '#565EEF',
    primaryHover: '#33399b',
    primaryButtonText: '#FFFFFF',
    accent: '#009EE4',
    accentHover: '#0080C1',
    danger: '#FF0000',
    border: '#D4DBE5',
    borderLight: '#D0CECE',
    inputBg: 'transparent',
    popupBg: '#FFFFFF',
    outlineButtonHoverBg: '#565EEF',
    toggleTrack: '#EAEEF6',
    toggleThumb: '#94A6BE',
    toggleThumbChecked: '#565EEF',
  },
};

export const darkTheme = {
  mode: 'dark',
  colors: {
    pageBg: '#151824',
    wrapperBg: '#0F111A',
    headerBg: '#2B2D3D',
    cardBg: '#2E3040',
    text: '#FFFFFF',
    mutedText: '#8F9BB3',
    primary: '#6A5ACD',
    primaryHover: '#5B4BBE',
    primaryButtonText: '#FFFFFF',
    accent: '#33B2FF',
    accentHover: '#1F9BE5',
    danger: '#FF7B7B',
    border: 'rgba(148, 166, 190, 0.4)',
    borderLight: '#4A4D5C',
    inputBg: '#252836',
    popupBg: '#2B2D3D',
    outlineButtonHoverBg: '#6A5ACD',
    toggleTrack: '#252836',
    toggleThumb: '#8F9BB3',
    toggleThumbChecked: '#6A5ACD',
  },
};

